### ISSUE TITLE
AttributeError: 'MultiDiscrete' object has no attribute 'n'

### ISSUE THREAD

**Issue by hzxwonder** [DKuan/MADDPG_torch#7]
The job is wonderful! But when I want to run "python main_openai.py --scenario_name simple_world_comm --display",it show me an error like this, it seems that it can't deal with the problem with more than two kinds of agents.Is there anything I can do to solve the problem? Thank you!
![ERROR](https://user-images.githubusercontent.com/52537483/141406013-8cd048cf-a7d7-4bbb-aee4-170dc81e5411.jpg)

**Comment by DKuan** [comment]
The aim of this code is to getting the number of the shape for the agent's action, so you can solve this problem by another code which gets this information.
